### ISSUE TITLE
BazelCASDatabase: put/get

### ISSUE THREAD

**Issue by tschuett** [apple/swift-llbuild2#97]
Out of curiosity: Is there a reason that the  `let resource =` expressions differ between put and get in 
`BazelCASDatabase`? put("foo") followed by get"foo") seems impossible?!?

**Comment by dmbryson** [comment]
From my understanding of the Bazel remote API, the put target is indeed supposed to go to a different resource than the get.  My very limited testing with a buildbarn instance running in Docker showed this to work.   Note however, the code is rather untested at this time.

**Comment by tschuett** [comment]
Sorry for the confusion. RE2 indeed defines different paths for put and get:
https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L210-L236
